# Generated by Django 5.2 on 2025-05-26 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image_library/')),
                ('category', models.CharField(choices=[('event', 'Event'), ('venue', 'Venue'), ('banner', 'Banner'), ('profile', 'Profile'), ('other', 'Other')], default='other', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Library',
                'ordering': ['-upload_date'],
            },
        ),
    ]
